services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    environment:
      MINIO_ACCESS_KEY: $ACCESS_KEY
      MINIO_SECRET_KEY: $SECRET_KEY
    command: server --console-address ":9001" /data

volumes:
  minio:
