services:
  minio:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z-cpuv1
    ports:
      - 9000:9000 # API
      - 9001:9001 # console
    volumes:
      - minio:/data
    # TODO: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated. Use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
    environment:
      MINIO_ACCESS_KEY: $OBJECT_STORAGE_ACCESS_KEY
      MINIO_SECRET_KEY: $OBJECT_STORAGE_SECRET_KEY
    command: server /data --console-address ":9001" --address ":9000"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 3

  create-buckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set my_minio http://minio:9000 adminadmin adminadmin;
      /usr/bin/mc admin info my_minio;
      /usr/bin/mc mb my_minio/some-bucket;
      /usr/bin/mc admin trace --verbose my_minio;"

volumes:
  minio:
