version: "3.8"

services:
  api-db:
    image: postgres:12.14
    container_name: api-db
    ports:
      - "${POSTGRES_EXPOSED_PORT}:5432"
    env_file:
      - .env
    volumes:
      - api-db:${PGDATA}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U typeorm"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - integration-tests

  api:
    image: api
    container_name: api
    volumes:
      - api:${APP_WORKDIR}
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - "${APP_EXPOSED_PORT}:${APP_PORT}"
    depends_on:
      - api-db
    profiles:
      - integration-tests
    environment:
      NODE_ENV: development
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "node", "/healthcheck.js"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  api-db:
  api:
