services:
  api:
    build:
      context: .
      target: development
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:debug
