services:
  app:
    image: app
    build: .
    container_name: app-container
    depends_on:
      app-db:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}

  app-db:
    image: mongo:8.0.0-rc17-noble
    container_name: app-database
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
